# Generated by Django 6.0.1 on 2026-01-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_userpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='dashboard_widgets',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='report_categories',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
