# Generated by Django 6.0.1 on 2026-01-17 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Sáng'), ('dark', 'Tối'), ('auto', 'Tự động')], default='light', max_length=20)),
                ('primary_color', models.CharField(default='#3B82F6', max_length=20)),
                ('sidebar_collapsed', models.BooleanField(default=False)),
                ('default_report_period', models.CharField(choices=[('week', 'Tuần'), ('month', 'Tháng'), ('quarter', 'Quý'), ('year', 'Năm')], default='month', max_length=20)),
                ('report_categories', models.JSONField(blank=True, default=list)),
                ('report_include_charts', models.BooleanField(default=True)),
                ('report_include_tables', models.BooleanField(default=True)),
                ('report_email_frequency', models.CharField(choices=[('never', 'Không gửi'), ('daily', 'Hàng ngày'), ('weekly', 'Hàng tuần'), ('monthly', 'Hàng tháng')], default='never', max_length=20)),
                ('notify_budget_exceeded', models.BooleanField(default=True)),
                ('notify_large_transaction', models.BooleanField(default=True)),
                ('notify_anomaly_detected', models.BooleanField(default=True)),
                ('large_transaction_threshold', models.DecimalField(decimal_places=2, default=1000000, max_digits=15)),
                ('dashboard_widgets', models.JSONField(blank=True, default=list)),
                ('dashboard_chart_type', models.CharField(choices=[('line', 'Đường'), ('bar', 'Cột'), ('pie', 'Tròn')], default='line', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
