# Generated by Django 6.0.1 on 2026-01-17 14:23

import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_userpreferences_dashboard_widgets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='dashboard_widgets',
            field=models.JSONField(blank=True, default=finance.models.default_list),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='report_categories',
            field=models.JSONField(blank=True, default=finance.models.default_list),
        ),
    ]
